<HTML>
<HEAD>
<meta charset="UTF-8">
<title>ResolvedConfiguration.rethrowFailure - api</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">api</a>&nbsp;/&nbsp;<a href="../index.html">org.gradle.api.artifacts</a>&nbsp;/&nbsp;<a href="index.html">ResolvedConfiguration</a>&nbsp;/&nbsp;<a href="./rethrow-failure.html">rethrowFailure</a><br/>
<br/>
<h1>rethrowFailure</h1>
<a name="org.gradle.api.artifacts.ResolvedConfiguration$rethrowFailure()"></a>
<code><span class="keyword">abstract</span> <span class="keyword">fun </span><span class="identifier">rethrowFailure</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a></code>
<p>A resolve of a configuration that is not successful does not automatically throws an exception. Such a exception is only thrown if the result of a resolve is accessed. You can force the throwing of such an exception by calling this method. 
<p>This method does nothing when resolution was successful.</p>
</p>
<h3>Exceptions</h3>
<p><a name="ResolveException"></a>
<code>ResolveException</code> - when the resolve was not successful.</p>
</BODY>
</HTML>
