<HTML>
<HEAD>
<meta charset="UTF-8">
<title>TestResult.getException - api</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">api</a>&nbsp;/&nbsp;<a href="../index.html">org.gradle.api.tasks.testing</a>&nbsp;/&nbsp;<a href="index.html">TestResult</a>&nbsp;/&nbsp;<a href=".">getException</a><br/>
<br/>
<h1>getException</h1>
<a name="org.gradle.api.tasks.testing.TestResult$getException()"></a>
<code><span class="identifier">@Nullable</span> <span class="keyword">abstract</span> <span class="keyword">fun </span><span class="identifier">getException</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a></code>
<p>If the test failed with an exception, this will be the exception. Some test frameworks do not fail without an exception (JUnit), so in those cases this method will never return null.</p>
<p><strong>Return</strong><br/>
The exception, if any, logged for this test. If none, a null is returned.</p>
</BODY>
</HTML>
